---
title: "CSX_R homework 3"
author: "Ymc"
date: "2018/03/20"
output: html_document
---
my site: https://b04902122.github.io/CSX_R/week_3/ggplot2.html
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ggplot2

```{r}
library(ggplot2)
```

## bar chart
```{r}
ggplot(data=iris, aes(x=Species, y=Sepal.Length, fill=Species)) +
    geom_bar(stat="identity") +
    guides(fill=FALSE)
```

## pie chart
```{r}
ggplot(data = iris,
  aes(x = factor(""), fill = Species) ) +
  geom_bar() +
  coord_polar(theta = "y") +
  scale_x_discrete("")
```

## scatter chart
```{r}
ggplot(iris, aes(Sepal.Length, Sepal.Width, color=Species)) +
  geom_point()
```

## scatter with trend line chart
```{r}
ggplot(data=iris,aes(x=Sepal.Width, y=Sepal.Length,color=Species)) + geom_point() +geom_smooth(se=FALSE)+
 theme_minimal()
```

## line chart
```{r}
ggplot(iris, aes(Sepal.Length, Sepal.Width, color=Species)) +
  geom_line()
```

## histogram chart
```{r}
ggplot(data = iris, aes(x = Sepal.Length,color=Species)) +
geom_histogram()
```

## frequency polygons chart
```{r}
ggplot(iris, aes(x=Petal.Length, color=Species)) +
  geom_freqpoly()
```

## boxplot chart
```{r}
ggplot(iris, aes(x=Petal.Length, y=Petal.Width, color=Species)) +
geom_boxplot()
```

## density curve chart
```{r}
ggplot(data=iris,aes(x=Sepal.Length,color=Species)) + geom_density() +theme_minimal()
```

## density2d curve chart
```{r}
ggplot(data=iris,aes(x=Petal.Width,y=Petal.Length,color=Species)) +geom_density2d()+ theme_minimal()
```
